name: Update Templates

on:
  push:
    branches:
      - main
    paths:
      - "tableData/src/tableData.json"
      - "src/assets"
      - "src/helpers"
      - "src/partials"
      - "src/templates"

  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod


permissions:
  id-token: write
  contents: write

jobs:
  load_templates_files:
    name: Upload Templates Files in Storage ${{(inputs == null && 'dev') || inputs.environment }}
    runs-on: [ self-hosted-job, "${{(inputs == null && 'dev') || inputs.environment }}" ]
    environment: ${{(inputs == null && 'dev') || inputs.environment }}
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: setup python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.10' # install the python version needed

      - name: execute py script # run main.py
        run: |
          cd scripts
          python create_templates_zip.py

      - name: Run Load Template Data Script
        shell: bash
        run: |
          export BLOB_CONN_STRING='${{ secrets.BLOB_CONN_STRING }}'
          cd ./tableData
          chmod +x ./loadTemplates.sh
          ./loadTemplates.sh ${{( inputs == null && 'dev') || inputs.environment }}
  
  load_template_metadata:
    name: Upload Templates Metadata in Table ${{(inputs == null && 'dev') || inputs.environment }}
    runs-on: [ self-hosted-job, "${{(inputs == null && 'dev') || inputs.environment }}" ]
    environment: ${{(inputs == null && 'dev') || inputs.environment }}
    steps:

      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Login
        id: login
        # from https://github.com/Azure/login/commits/master
        uses: azure/login@92a5484dfaf04ca78a94597f4f19fea633851fa2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Run Load Template Data Script
        shell: bash
        run: |
          export BLOB_CONN_STRING='${{ secrets.BLOB_CONN_STRING }}'
          cd ./tableData
          chmod +x ./loadTableData.sh
          ./loadTableData.sh ${{( inputs == null && 'dev') || inputs.environment }}

  update_template_examples:
    name: Update PDF examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4 # Aggiornato a v4 per best practice
        with:
          token: ${{ secrets.BOT_TOKEN_GITHUB }}

      - name: Setup Node.js v22 and Yarn
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.x'
          #cache: 'yarn'

      - name: Install system dependencies for Puppeteer
        run: |
          export RUNNER_ALLOW_RUNASROOT="1"
          sudo apt-get update
          sudo apt-get install -y \
            libxkbcommon0 \
            libgtk-3-0 \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libatk-bridge2.0-0 \
            libgbm1 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libatk1.0-0 \
            libcups2 \
            libdrm2

      - name: Install Node.js dependencies
        run: yarn install --frozen-lockfile

      - name: Run Generate Template Examples Script
        shell: bash
        run: |
          cd ./scripts
          chmod +x ./generateExamples.sh
          ./generateExamples.sh  
          cd ..

      - name: Commit files
        run: |
          git config --local user.email "pagopa-github-bot@pagopa.it"
          git config --local user.name "pagopa-github-bot"
          git commit -a -m "Examples Updated [skip-ci]" || exit 0
          git push